### ISSUE TITLE
Device "auto rotate" settings are overwritten.

### ISSUE THREAD

**Issue by giuspe** [fhem/nina#2]
#### Scenario

  - as phone user, I've switched off my "auto rotate" setting.
  - I use the application and flip my screen horizontally and vertically

#### Expected result

the application layout and the screen orientation of my phone don't change.

#### Actual result

screen orientation changes (portrait / landscape).

#### Environment information

  - Pixel 2 (`walleye`) phone
  - Android 11 OTA, but confirmed on Android 10 as well
  - bootloader unlocked, but phone not rooted
  - app Version: 3.2.1, Build: 2720

**Comment by christoph-morrison** [comment]
Wrong neighborhood.
